version: "3.9"

name: cadastro-tarefas

services:

  db:
    image: mysql:9.7

    container_name: cadastro-tarefas-db

    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "${MYSQL_PORT}:3306"

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

    networks:
      - cadastro-tarefas-network

  backend:

    build:
      context: ./

    image: cadastro-tarefas-back:latest

    container_name: cadastro-tarefas-backend

    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "8080:8080"

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-q",
          "http://localhost:8080/actuator/health"
        ]
      interval: 20s
      timeout: 5s
      retries: 10

    networks:
      - cadastro-tarefas-network

  frontend:

    build:
      context: ./../cadastro-tarefas-front

    image: cadastro-tarefas-front:latest

    container_name: cadastro-tarefas-frontend

    restart: unless-stopped

    depends_on:
      backend:
        condition: service_started

    environment:
      API_URL: http://localhost:8080

    ports:
      - "4200:80"

    networks:
      - cadastro-tarefas-network

volumes:
  mysql-data:

networks:
  cadastro-tarefas-network:
    driver: bridge